spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  reset-token-expiry-days: 2